### ISSUE TITLE
Drop-in replacement for Web3ReactProvider getting error, packages core is loading fine (v6)

### ISSUE THREAD

**Issue by LarryRyan0824** [Uniswap/web3-react#649]
The app works fine with the core package, but I am looking to make some modifications. If I take the v6.1.9 core files and drop them into my project and replace import { Web3ReactProvider } from '@web3-react/core' with import { Web3ReactProvider } from './config/web3Core', I get this error

Error place 1 Error: Invariant failed: No <Web3ReactProvider ... /> found.
    at invariant (tiny-invariant.esm.js:15:1)
    at activate (core.esm.js:527:1)
    at EthContext.jsx:260:1
    at inject (connectionHooks.js:124:1)

Everything is set the same as before, besides where I import it from. Is there something special I should be doing?

**Comment by LarryRyan0824** [comment]
I overlooked some things, you need to go through the app and replace all the useWeb3React directories to point there too.
