### ISSUE TITLE
initializeConnector<MetaMask> error

### ISSUE THREAD

**Issue by 0xf2dd55** [Uniswap/web3-react#662]
Hello,

I'm trying to migrate a project from v6 to v8 but I'm stuck on the first instruction ! ;)

`
import { MetaMask } from '@web3-react/metamask'
import { initializeConnector } from '@web3-react/core'

export const [MM, hooks] = initializeConnector<MetaMask>( (actions) => new MetaMask(actions))
`

Just with that I have the following error :

`Uncaught TypeError: boolean false is not iterable (cannot read property Symbol(Symbol.iterator))
    at Module.<anonymous> (ConnectButton.js:9:1)
    at ./src/ConnectButton.js (ConnectButton.js:66:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (App.css?dde5:82:1)
    at ./src/App.js (App.js:55:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (ccfunctions.js:160:1)
    at ./src/index.js (index.js:19:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at 1 (reportWebVitals.js:14:1)
    at __webpack_require__ (bootstrap:856:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:65`

I'm using react 18.2 and "@web3-react/core": "^8.0.35-beta.0" and "@web3-react/metamask": "^8.0.28-beta.0" which are the latest I guess.

Any help would be greatly appreciated, have a nice day !

**Comment by vm** [comment]
what's the code for ConnectButton look like? error seems somewhat unrelated to the snippet you shared

**Comment by 0xf2dd55** [comment]
Well, in fact the plain file is just :
'import React, { useEffect } from 'react';
import { Button } from 'react-bootstrap';
import * as CC from './ccfunctions';

import { MetaMask } from '@web3-react/metamask'
import { initializeConnector } from '@web3-react/core'

//export const [MM, hooks] = initializeConnector<MetaMask>( (actions: any) => new MetaMask({ actions, options: { silent: true } }))
export const [MM, hooks] = initializeConnector<MetaMask>( (actions) => new MetaMask(actions))
'

I do nothing more and just import the ConnectButton from App.js, line 9 is the initializeConnector line.

**Comment by 0xf2dd55** [comment]
I tried directly in App.js without anything but the bare default stuff and still have the same error on the initializeConnector line :(

If anyone has a suggestion, it would be really welcome. Thanks.

![Capture d’écran 2022-09-03 à 17 54 56](https://user-images.githubusercontent.com/111143013/188273667-00bc4fa8-12a9-4420-a970-4ed15298f8c3.png)

![Capture d’écran 2022-09-03 à 17 56 07](https://user-images.githubusercontent.com/111143013/188273676-03bb5237-ec0f-45a9-b6d7-f4beef78da61.png)

**Comment by 0xf2dd55** [comment]
I just tried to create a new empty React project with `npx create-react-app testw3`, just added the 3 following lines : 
`
import { initializeConnector } from '@web3-react/core'
import { MetaMask } from '@web3-react/metamask'
export const [metaMask, hooks] = initializeConnector<MetaMask>((actions) => new MetaMask({ actions }))
`
and the following to the default package.json : 
`
    "@web3-react/core": "^8.0.35-beta.0",
    "@web3-react/metamask": "^8.0.28-beta.0",
`
I still have the exact same issue. Is there any npm package version requirement I could break ? Something to check ?
Thanks
