### ISSUE TITLE
Incompatibility with zustand@4.3.4

### ISSUE THREAD

**Issue by anatoliiuspensky** [Uniswap/web3-react#765]
Get the following error when trying to connect to network or metamask:
```
TypeError: (0 , zustand_1.createStore) is not a function
    at createWeb3ReactStoreAndActions (/app/node_modules/@web3-react/store/dist/index.js:27:45)
    at initializeConnector (/app/node_modules/@web3-react/core/dist/hooks.js:66:73) 
```

started after zunstand updated to version 4.3.4

**Comment by hathbanger** [comment]
https://github.com/Uniswap/web3-react/pull/767
