### ISSUE TITLE
@web3-react/core": "^8.0.36-beta.0" - error

### ISSUE THREAD

**Issue by hyunkyung-cv** [Uniswap/web3-react#772]
unhandledRejection TypeError: (0 , zustand_1.createStore) is not a function
    at createWeb3ReactStoreAndActions (/Users/hyunkyung/workspace/cling_swap/cling-swap-web/node_modules/@web3-react/store/dist/index.js:27:45)
    at initializeConnector (/Users/hyunkyung/workspace/cling_swap/cling-swap-web/node_modules/@web3-react/core/dist/hooks.js:63:73)
    at Object.996 (/Users/hyunkyung/workspace/cling_swap/cling-swap-web/.next/server/chunks/727.js:1173:96)
    at __webpack_require__ (/Users/hyunkyung/workspace/cling_swap/cling-swap-web/.next/server/webpack-runtime.js:25:42)
    at /Users/hyunkyung/workspace/cling_swap/cling-swap-web/.next/server/pages/_app.js:3229:82
    at Function.__webpack_require__.a (/Users/hyunkyung/workspace/cling_swap/cling-swap-web/.next/server/webpack-runtime.js:89:13)
    at Object.6505 (/Users/hyunkyung/workspace/cling_swap/cling-swap-web/.next/server/pages/_app.js:3218:21)
    at __webpack_require__ (/Users/hyunkyung/workspace/cling_swap/cling-swap-web/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/Users/hyunkyung/workspace/cling_swap/cling-swap-web/.next/server/pages/_app.js:3950:39)
    at /Users/hyunkyung/workspace/cling_swap/cling-swap-web/.next/server/pages/_app.js:3951:94 {
  type: 'TypeError'
}

**Comment by yoreeeeeeeeee** [comment]
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/120449617/221826809-454f24de-8b01-4c63-863f-fb3d796d98ef.png">
I am experiencing the same issue. Could you please review and suggest a solution?

**Comment by Christopher-Stevers** [comment]
I've seen the same error as well.

**Comment by grabbou** [comment]
This is already fixed, please upgrade to latest version available.

**Comment by yoreeeeeeeeee** [comment]
@grabbou Thanks, I'll help you check if our service is working properly.
