### ISSUE TITLE
WalletConnectV2 TypeError: Og2.default.init is not a function #840

### ISSUE THREAD

**Issue by ersanyakit** [Uniswap/web3-react#861]
Seeing an error when trying to use wallet connect in our dapp when deployed on IPFS.
`
activate.ts:57 TypeError: Og2.default.init is not a function
    at hr2.createClient (index.cjs.js:27:29719)
    at hr2.initialize (index.cjs.js:27:29572)
    at hr2.init (index.cjs.js:27:26718)
    at I2.initialize (index.cjs.js:1:6874)
    at I2.init (index.cjs.js:1:2663)
    at WalletConnectV2.<anonymous> (index.js:87:79)
    at Generator.next (<anonymous>)
    at fulfilled (tslib.js:112:62)
`

<img width="596" alt="Ekran Resmi 2023-07-21 17 13 36" src="https://github.com/Uniswap/web3-react/assets/10724463/4c9dabbe-18fd-40db-b9ea-662f2944d60f">

Test URL : https://imon.ai

**Comment by Nookee411** [comment]
> Im using VITEJS + React TS
> 
> Seeing an error when trying to use wallet connect in our dapp when deployed on IPFS. `activate.ts:57 TypeError: Og2.default.init is not a function at hr2.createClient (index.cjs.js:27:29719) at hr2.initialize (index.cjs.js:27:29572) at hr2.init (index.cjs.js:27:26718) at I2.initialize (index.cjs.js:1:6874) at I2.init (index.cjs.js:1:2663) at WalletConnectV2.<anonymous> (index.js:87:79) at Generator.next (<anonymous>) at fulfilled (tslib.js:112:62)`
> 
> <img alt="Ekran Resmi 2023-07-21 17 13 36" width="596" src="https://user-images.githubusercontent.com/10724463/255198734-4c9dabbe-18fd-40db-b9ea-662f2944d60f.png">
> Test URL : https://imon.ai

Have you managed to resolve this issue?

**Comment by ersanyakit** [comment]
yes,  its fixed. just update your vite.config.ts 

<img width="932" alt="Ekran Resmi 2023-07-29 08 59 14" src="https://github.com/Uniswap/web3-react/assets/10724463/6e81dc2d-4001-4124-8f40-d7cb079c7d51">

`    alias: {
      '@walletconnect/ethereum-provider': '../../../@walletconnect/ethereum-provider/dist/index.es.js',
      '@walletconnect/utils': '../../../@walletconnect/utils/dist/index.umd.js',
      '@': path.resolve(__dirname, './src'),
    }`

**Comment by chris13524** [comment]
I think this issue is related to #840 and a potential fix in web3-react without updating packaging is here: https://github.com/Uniswap/web3-react/issues/840#issuecomment-1613619864

**Comment by christiecc8** [comment]
@ersanyakit thank you for the workaround, it worked for me. bumping this issue
